#!/bin/bash

#PBS -q normal
#PBS -l select=1:ncpus=24:mpiprocs=4:ompthreads=6
#PBS -l walltime=1:00:00
#PBS -m ae
#PBS -P 50000043
#PBS -N GROMACS
#PBS -o /home/project/50000043/apacsc29/GROMACS/JobOutput/ligno-new-7
#PBS -e /home/project/50000043/apacsc29/GROMACS/JobOutput/ligno-new-er-7


module load singularity
export PROJ="/home/project/50000043/apacsc29/GROMACS"
export SIF=$PROJ/sif/gmx-intel-ompi-gpu-release.sif
export GMXRUN="/home/runsh"

cd $PROJ
singularity exec -B $PROJ:/home $SIF bash $GMXRUN/run_lignocellulose-7.sh

